baseURL = ''
languageCode = 'en-uk'
defaultContentLanguage = 'en'
enableRobotsTXT = true
title = 'pyhugodoc'
ignoreFiles = [ '_api-reference/*' ]
theme = 'hugo-theme-learn'

[params]
  editURL = "https://github.com/anand2312/pyhugodoc/tree/main/docs/content/"
  author = "Anand Krishna"
  description = "Build beautiful documentation for your Python projects."
  disableLandingPageButton = true
[outputs]
  home = ["HTML", "RSS", "JSON"]

[menu]
  [[menu.shortcuts]]
    name = "<i class='fab fa-github'></i> Github repo"
    identifier = "ds"
    url = "https://github.com/anand2312/pyhugodoc"
    weight = 10
